第5回　コード
shun74/pytorch-training pull request #13
Opened 2023-11-26 05:49 UTC by anryu15

スライドのコメントお願いします。

https://docs.google.com/presentation/d/1yDFP1_lsLxyqdDjbXRKOOTg-mbnRMi4VHE6DxHpEjPg/edit?usp=sharing

2023-11-26 06:53 UTC, shun74 requested changes
修正をお願いします。

2023-11-26 06:53 UTC, shun74 commented on codes/05/.DS_Store
このファイルは消してください

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/.DS_Store
このファイルは消してください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/example/mydataset.py
> +        self.dataset_dir = Path(dataset_dir).resolve()
`self.dataset_dir`はクラスの他の部分で使われていないので、`dir_path_resolved`などの一時変数に置き換えてください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/example/mydataset.py
> +        self.img_list = list(self.dataset_dir.glob("*"))
今回はpngフォーマットの画像を扱っているので`*.png`としてください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/example/mydataset_trans.py
> +        self.dataset_dir = Path(dataset_dir).resolve()
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/example/mydataset_trans.py
> +        self.img_list = list(self.dataset_dir.glob("*"))
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/example/mydataset_trans.py
> +        label = parts[-1][:3]
ファイル名からラベルを取得していることをコメントで簡単に書いてください。
これはラベルなので`int(parts[-1][:3])`のように書いて型を数値型にしてください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise2.py
> +        self.dataset_dir = Path(dataset_dir).resolve()
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise2.py
> +        self.paths = list(self.dataset_dir.glob("*"))
`self.paths`は一時変数なので、`dir_list`などの一時変数に変更してください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise2.py
> +            self.img_path_list = list(i.glob("*"))
`self.img_path_list`は一時変数なので`img_path_list`にしてください。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +        self.dataset_dir = Path(dataset_dir).resolve()
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +        self.paths = list(self.dataset_dir.glob("*"))
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +            self.img_path_list = list(i.glob("*"))
同様の変更が必要です。

2023-11-26 06:53 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +        label = parts[-2]
フォルダ名からラベルを取得していることを簡単に書いてください。
これはラベルなので`int(parts[-2])`のように書いて型を数値型にしてください。

2023-11-26 08:50 UTC, shun74 commented
スライドの修正が終わったら`Re-request review`をかけてください。

2023-11-27 03:18 UTC, shun74 requested changes
使用されていないライブラリはimportから排除してください。

2023-11-27 03:18 UTC, shun74 commented on codes/05/example/mydataset_trans.py
> +import matplotlib.pyplot as plt
使用されていないライブラリなので消してください。

2023-11-27 03:18 UTC, shun74 commented on codes/05/example/mydataset_trans.py
> +import torch
同じく使用されていないです。

2023-11-27 03:18 UTC, shun74 commented on codes/05/exercise/exercise2.py
> +import matplotlib.pyplot as plt
使用されていないライブラリです。

2023-11-27 03:18 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +import matplotlib.pyplot as plt
使用されていないライブラリです。

2023-11-27 03:18 UTC, shun74 commented on codes/05/exercise/exercise3.py
> +import torch
同じく使用されていません。

2023-11-27 14:46 UTC, shun74 submitted a review, later dismissed
LGTM

2023-11-27 15:25 UTC, Kosuke-Sugimoto commented on codes/03/exercise/exercise2.py
WANT
このPRで触れるのは第五回の内容に関連するモノのみにしたいので余裕があれば対応してください

2023-11-27 15:26 UTC, Kosuke-Sugimoto commented on slides/05/pytorch05.pdf
修正後のpdfへの差し替えを忘れないようにしてください
危なそうならこのアップは取り消す方向で

2023-11-27 15:26 UTC, Kosuke-Sugimoto commented on slides/05/pytorch05.pptx
修正後のpptxへの差し替えを忘れないようにしてください
危なそうならこのアップは取り消す方向で

2023-11-27 15:28 UTC, Kosuke-Sugimoto commented on codes/05/exercise/exercise1.py
> +        print(dir)
WANT
出力が汚くなる（昇順or降順でない）気がするので、sortを入れても良い気がします

2023-11-27 15:40 UTC, Kosuke-Sugimoto commented on codes/05/example/mydataset_trans.py
> +        label = int(parts[-1][:3])
WANT
Path.partsに関しては急に出てきているので、説明は入れた方が良いと思います
また、26行目に関しても少々分かりづらい気がするので、コメントを入れるか
分割して分かりやすい変数名の変数に格納するなどした方が良い気がします

2023-11-27 15:46 UTC, Kosuke-Sugimoto commented on codes/05/example/path_example.py
> +        return []
WANT
assertかraiseで良い気もします
何か意図があったのであればすみません

2023-11-27 15:48 UTC, Kosuke-Sugimoto commented on codes/05/example/path_example.py
> +
WANT
余分な空行な気がするので、できれば消してください

2023-11-27 15:51 UTC, Kosuke-Sugimoto commented on codes/05/exercise/exercise2.py
> +            self.img_list += img_path_list
WANT
初心者的にはこの表記が分かるか怪しいので、コメントを入れるか
extendを使うかにした方が良い気がします

2023-11-27 15:52 UTC, Kosuke-Sugimoto reviewed
確認しました。
いくつかコメントしたので対応よろしくお願いします
スライドの方にもコメント追加しました

2023-11-27 16:43 UTC, shun74 commented on codes/05/exercise/exercise1.py
> +        print(dir)
確かに`sorted(list())`を使った方が参考になり増す。

2023-11-27 16:46 UTC, shun74 commented on codes/05/example/path_example.py
> +        return []
@anryu15 
ここは`assert`で対応しましょう。`raise`だと処理が停止してしまうので今回は使わないで大丈夫です。

2023-11-27 16:48 UTC, shun74 commented on slides/05/pytorch05.pdf
@anryu15 
一度pdfとpptxを削除するコミットを行ってください。
Approveがもらえたらpdfとpptxを再度コミットしてからマージしましょう。
コミットし忘れても別PRでpdfとpptxをマージしてもらえれば大丈夫です。

2023-11-28 00:14 UTC, shun74 commented on codes/05/example/path_example.py
> +        return []
すいません。`assert`でも普通に処理は止まりますね。
`Error`という単語を使うと処理を止めないといけない雰囲気になるので、今回のケースでは`Warning`という単語を使うのが適切です。
また、デバッグがしやすいようにメッセージの中で、どのディレクトリが無かったのかを示してあげるとよりよいメッセージになります。

なので今回は、
1. 処理を止めるつもりはない→`Error`を`Warning`にする。
2. `Error`として処理したい→`assert`を使う。
のどちらかで修正してください。

2023-11-28 15:01 UTC, anryu15 commented on codes/03/exercise/exercise2.py
すみません

2023-11-28 15:09 UTC, anryu15 commented on codes/05/example/path_example.py
> +        return []
assertで対応しました。
closeします。

2023-11-28 15:10 UTC, anryu15 commented on codes/05/example/path_example.py
> +
対応しました。
closeしました。

2023-11-28 15:19 UTC, Kosuke-Sugimoto approved these changes
LGTM

2023-11-28 15:20 UTC, merged