add example code
shun74/pytorch-training pull request #18
Opened 2023-12-19 15:19 UTC by hdhono

下記の追加を行いました。確認お願いします。
train.py : 前回のトレーニングのスクリプトに保存部分を追加
evaluation.py : 保存したモデルの読み込み・テストデータで精度を評価

2023-12-19 15:38 UTC, shun74 requested changes

2023-12-19 15:38 UTC, shun74 commented on codes/08/example/evaluation.py
> +criterion = nn.CrossEntropyLoss()
evaluation.pyは精度の評価だけでいいので`loss`を計算している部分などは消してください。

2023-12-19 16:05 UTC, Kosuke-Sugimoto approved these changes
LGTM

2023-12-19 16:11 UTC, Kosuke-Sugimoto commented on codes/08/example/evaluation.py
> +criterion = nn.CrossEntropyLoss()
@hdhono 
accuracyの計算にcriterionは使わないので定義から消しちゃってよい気がします
また、それに伴い loss = criterion(~) の部分も消しちゃってよいかと

2023-12-19 17:47 UTC, shun74 commented
@hdhono 
スライドを更新したので修正したものをプッシュしてください。

2023-12-20 03:57 UTC, shun74 approved these changes
LGTM

2023-12-20 03:57 UTC, merged