PyTorch 講座　第三回
shun74/pytorch-training pull request #8
Opened 2023-11-11 14:35 UTC by Kosuke-Sugimoto

第三回のコードに関するマージ
スライドは
https://docs.google.com/presentation/d/1GcPBZ56-o7H_uAw9s_B7_DC7tPQ3MTp1Eh0yM_xZmpU/edit?usp=sharing
にあります
スライドに関してはコメントをお願いします
コメント対応終了後、別途PR送ります

2023-11-11 15:08 UTC, shun74 commented on env/docker_run.sh
> -    docker build -t $DOCKER_IMAGE_NAME .
この部分は差分を取り消して別のブランチで修正するPRを出してください。

2023-11-11 18:36 UTC, Kosuke-Sugimoto commented on env/docker_run.sh
> -    docker build -t $DOCKER_IMAGE_NAME .
対応しました

2023-11-11 18:40 UTC, Kosuke-Sugimoto commented on env/docker_run.sh
> -    docker build -t $DOCKER_IMAGE_NAME .
修正用のPRは本PR実行後に出します

2023-11-12 07:13 UTC, shun74 requested changes
スライドへのコメントと合わせてレビューをしました。
修正をお願いします。

2023-11-12 07:13 UTC, shun74 commented on codes/03/exercise/exercise1.py
> +    print(repr(permuted_tensor))
sizeも表示した方がいいです。

2023-11-12 07:13 UTC, shun74 commented on codes/03/exercise/exercise1.py
> +    tensor = torch.tensor(data, dtype=float)
`torch.tensor`がある中で`tensor`という名前の変数を作るのは不適切なので、`T`や`A`など別の名前に変えてください。

2023-11-12 07:15 UTC, shun74 commented on codes/03/exercise/exercise2.py
> +        self.tensor = tensor
ここも`tensor`という名前が使われているので変更してください。

2023-11-13 14:47 UTC, Kosuke-Sugimoto commented on codes/03/exercise/exercise1.py
> +    tensor = torch.tensor(data, dtype=float)
tensor から _tensor に変更しました

2023-11-13 14:47 UTC, Kosuke-Sugimoto commented on codes/03/exercise/exercise2.py
> +        self.tensor = tensor
tensor から mytensor に変更しました

2023-11-13 15:07 UTC, Kosuke-Sugimoto commented
@shun74 
Google Slide のコメント対応、それに伴うコードの修正が完了しました。
確認お願いします

2023-11-13 23:32 UTC, shun74 reviewed
LGTM

2023-11-13 23:35 UTC, shun74 approved these changes, later dismissed

2023-11-14 04:39 UTC, hdhono approved these changes

2023-11-14 10:30 UTC, anryu15 approved these changes

2023-11-14 10:30 UTC, merged